// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xosczqqblnfdrwkjacxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvc2N6cXFibG5mZHJ3a2phY3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDcyODQsImV4cCI6MjA3MTc4MzI4NH0.H51_bCYJawipg85kKnl2s8xnbtucNJetF7jZNTRTl3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});